In [5]:
import packet_analyzer as pa
import matplotlib.pyplot as plt

In [2]:
df = pa.load_df("20230520_215517")

In [3]:
df.head()

,src_ip,dst_ip,src_port,dst_port,pid,process_creation_time_sec,process_name,transfer_direction,log_timestamp_sec,transfer_size_bytes
0,192.168.1.65,52.44.223.164,63854,443,15632,1.684273e+09,slack.exe,upload,2,163
1,192.168.1.65,44.226.178.27,60378,443,15632,1.684273e+09,slack.exe,upload,2,163
2,192.168.1.65,52.44.223.164,63854,443,15632,1.684273e+09,slack.exe,upload,3,163
3,192.168.1.65,44.226.178.27,60378,443,15632,1.684273e+09,slack.exe,upload,3,163
4,192.168.1.65,34.117.237.239,50203,443,34164,1.684458e+09,firefox.exe,upload,3,225

In [6]:
df["transfer_size_megabits"] = (df["transfer_size_bytes"] * 8 )/ 1e6

In [7]:
df.head()

,src_ip,dst_ip,src_port,dst_port,pid,process_creation_time_sec,process_name,transfer_direction,log_timestamp_sec,transfer_size_bytes,transfer_size_megabits
0,192.168.1.65,52.44.223.164,63854,443,15632,1.684273e+09,slack.exe,upload,2,163,0.001304
1,192.168.1.65,44.226.178.27,60378,443,15632,1.684273e+09,slack.exe,upload,2,163,0.001304
2,192.168.1.65,52.44.223.164,63854,443,15632,1.684273e+09,slack.exe,upload,3,163,0.001304
3,192.168.1.65,44.226.178.27,60378,443,15632,1.684273e+09,slack.exe,upload,3,163,0.001304
4,192.168.1.65,34.117.237.239,50203,443,34164,1.684458e+09,firefox.exe,upload,3,225,0.001800

In [8]:
system_time_series = df.groupby("log_timestamp_sec")["transfer_size_megabits"].sum()

In [18]:
system_time_series.index.tolist()

[2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59]